### ISSUE TITLE
error

### ISSUE THREAD

**Issue by yanhan13944047669** [carloscaetano/skeleton-images#6]
When I try to convert two skeleton files into two diagrams, the following error occurs:
ERROR	D:/UserData/yanhan/data/NTUskeletons/skeletons\S001C001P001R001A001.skeleton object of type 'int' has no len()
ERROR	D:/UserData/yanhan/data/NTUskeletons/skeletons\S001C001P001R001A002.skeleton object of type 'int' has no len()
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "D:\Users\yanhan\.conda\envs\pytorch_171\lib\multiprocessing\pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "D:\Users\yanhan\.conda\envs\pytorch_171\lib\multiprocessing\pool.py", line 44, in mapstar
    return list(map(*args))
  File "D:\UserData\yanhan\RE-ID CO\skeleton-images-master\skeleton-images-master\GenerateSkeletonImages.py", line 48, in worker
    ret = getattr(obj, method_name)(skl_file, path_to_save)
  File "D:\UserData\yanhan\RE-ID CO\skeleton-images-master\skeleton-images-master\ImgType.py", line 214, in process_skl_file
    del list_path_to_save
UnboundLocalError: local variable 'list_path_to_save' referenced before assignment
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:/UserData/yanhan/RE-ID CO/skeleton-images-master/skeleton-images-master/GenerateSkeletonImages.py", line 67, in <module>
    main(argparse.ArgumentParser())
  File "D:/UserData/yanhan/RE-ID CO/skeleton-images-master/skeleton-images-master/GenerateSkeletonImages.py", line 58, in main
    list_extraction = pool.map(worker, ((obj, 'process_skl_file', skl_file, args.path_to_save, args.temp_dist) for obj, skl_file in zip(obj_list, skl_list)))
  File "D:\Users\yanhan\.conda\envs\pytorch_171\lib\multiprocessing\pool.py", line 266, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "D:\Users\yanhan\.conda\envs\pytorch_171\lib\multiprocessing\pool.py", line 644, in get
    raise self._value
UnboundLocalError: local variable 'list_path_to_save' referenced before assignment

What is the reason and how will I solve the problem？
I hope my problem can be solved，thanks.

**Comment by lxlcry** [comment]
> 当我尝试将两个框架文件转换为两个图表时，出现以下错误： 错误 D：/UserData/yanhan/data/NTUskeletons/skeletons\S001C001P001R001A001.skeleton 类型为“int”的对象没有 len（） 错误 D：/UserData/yanhan/data/NTUskeletons/skeletons\S001C001P001R001A002.skeleton 类型为“int”的对象没有 len（） multiprocessing.pool.RemoteTraceback： “”“ 回溯（最近一次调用最后一次）：文件“D：\Users\yanhan.conda\envs\pytorch_171\lib\multiprocessing\pool.py”，第 119 行，在 worker result = （True， func（*args， **kwds）） 文件“D：\Users\yanhan.conda\envs\pytorch_171\lib\multiprocessing\pool.py”，第 44 行，在 mapstar return list（map（*args）） 文件“D：\UserData\yanhan\RE-ID CO\skeleton-images-master\skeleton-images-master\GenerateSkeletonImages.py”，第 48 行，在 worker ret = getattr（obj， method_name）（skl_file， path_to_save） 文件“D：\UserData\yanhan\RE-ID CO\skeleton-images-master\skeleton-images-master\ImgType.py”，第 214 行，在 process_skl_file del list_path_to_save UnboundLocalError：赋值前引用的局部变量“list_path_to_save” """
> 
> 上述异常是导致以下异常的直接原因：
> 
> 回溯（最近一次调用最后一次）：文件“D：/UserData/yanhan/RE-ID CO/skeleton-images-master/skeleton-images-master/GenerateSkeletonImages.py”，第 67 行，在 main（argparse.ArgumentParser（）） 文件“D：/UserData/yanhan/RE-ID CO/skeleton-images-master/skeleton-images-master/GenerateSkeletonImages.py”，第 58 行，在主list_extraction中 = pool.map（worker， （（obj， 'process_skl_file'， skl_file， args.path_to_save， args.temp_dist） for obj， skl_file in zip（obj_list， skl_list））） 文件 “D：\Users\yanhan.conda\envs\pytorch_171\lib\multiprocessing\pool.py”，第 266 行，在映射返回中 self._map_async（func， iterable， mapstar， chunksize）.get（） 文件“D：\Users\yanhan.conda\envs\pytorch_171\lib\multiprocessing\pool.py”，第 644 行，在 get raise self._value UnboundLocalError：赋值前引用局部变量“list_path_to_save”
> 
> 原因是什么，我将如何解决问题？ 我希望我的问题能得到解决，谢谢。
Have you resolved it? I made the same mistake
